apiVersion: v1
kind: ReplicationController
metadata: 
  name: test-ReplicationController
  labels: 
    app: test-ReplicationController
    type: front-end
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

# kubect run ngix --image=nginx