apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
  labels: 
    app: web-server
    type: front-end
spec:
  containers:
    - name : nginx
      image: nginx
    - name: redis
      image: redis123

# kubect run ngix --image=nginx